backend:
  name: test-repo

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "units"
    label: "🗄️ وحدات الحمام"
    folder: "data/units"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "كود المنتج (ID)", name: "id", widget: "string"}
      - {label: "اسم المنتج (عربي)", name: "titleAr", widget: "string"}
      - label: "التصنيف الفرعي"
        name: "category"
        widget: "select"
        options:
          - {label: "خشبيات (Wood)", value: "wood"}
          - {label: "رخاميات (Marble)", value: "marble"}
          - {label: "ألوان (Colors)", value: "colors"}
          - {label: "مستورد (Imported)", value: "imported"}
      - {label: "الصورة الرئيسية", name: "image", widget: "image"}

  - name: "general_products"
    label: "🛁 باقي المنتجات"
    folder: "data/products"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "كود المنتج (ID)", name: "id", widget: "string"}
      - {label: "اسم المنتج (عربي)", name: "titleAr", widget: "string"}
      - {label: "السعر", name: "price", widget: "number"}
      - {label: "الصورة الرئيسية", name: "image", widget: "image"}
